### ISSUE TITLE
Permissions requested in scanner deployment are too broad.

### ISSUE THREAD

**Issue by mikedanese** [heptio/sonobuoy#130]
Scanner currently deploys with a '*/*' cluster role in the installation guide here:

https://scanner.heptio.com/6301b0af8666df98addeaaf6c9b0f9a2/

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-serviceaccount
  namespace: heptio-sonobuoy
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
```

Can the set of permissions be reduced?

**Comment by timothysc** [comment]
@mikedanese do you know what the permissions are for the e2e test runs upstream?  

I couldn't find an RBAC config for the kubekins container.

/cc @ixdy ?

**Comment by chuckha** [comment]
hey @mikedanese I ran scanner with the audit log enabled and generated rbac permissions with [audit2rbac](https://github.com/liggitt/audit2rbac). What came out was a pretty huge list since the e2e tests exercise a lot of the API. If we went this route there would be a ton of maintenance involved in maintaining this list (api groups changing and whatnot).

I'd be interested to hear if there are any permissions you're particularly concerned about, but for now I think *** is going to be a requirement for running scanner.

Thanks so much for letting us know your concerns.

Here is the complete output from audit2rbac:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.5.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-heptio-sonobuoy-sonobuoy-serviceaccount
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
  namespace: heptio-sonobuoy
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - deletecollection
- apiGroups:
  - settings.k8s.io
  resources:
  - podpresets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.5.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-heptio-sonobuoy-sonobuoy-serviceaccount
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
  namespace: e2e-tests-svcaccounts-n5zx8
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.5.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-heptio-sonobuoy-sonobuoy-serviceaccount
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
  namespace: e2e-tests-replicaset-djcvr
rules:
- apiGroups:
  - extensions
  resources:
  - replicasets
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.5.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-heptio-sonobuoy-sonobuoy-serviceaccount
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
  namespace: e2e-tests-proxy-2kr5h
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - proxy
- apiGroups:
  - ""
  resourceNames:
  - proxy-service-6ppbh
  resources:
  - replicationcontrollers
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.5.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-heptio-sonobuoy-sonobuoy-serviceaccount
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - events
  - limitranges
  - persistentvolumeclaims
  - podtemplates
  - resourcequotas
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - proxy
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  - pods/log
  - pods/proxy
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - fooxmhq7as.mygroup.example.com
  resources:
  - customresourcedefinitions
  verbs:
  - delete
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - ingresses
  - networkpolicies
  - podsecuritypolicies
  - replicasets
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.example.com
  resources:
  - fooxmhq7as
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - mygroup.example.com
  resourceNames:
  - setup-instance
  resources:
  - fooxmhq7as
  verbs:
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.5.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-heptio-sonobuoy-sonobuoy-serviceaccount
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
  namespace: heptio-sonobuoy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
subjects:
- kind: ServiceAccount
  name: sonobuoy-serviceaccount
  namespace: heptio-sonobuoy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.5.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-heptio-sonobuoy-sonobuoy-serviceaccount
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
  namespace: e2e-tests-svcaccounts-n5zx8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
subjects:
- kind: ServiceAccount
  name: sonobuoy-serviceaccount
  namespace: heptio-sonobuoy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.5.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-heptio-sonobuoy-sonobuoy-serviceaccount
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
  namespace: e2e-tests-replicaset-djcvr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
subjects:
- kind: ServiceAccount
  name: sonobuoy-serviceaccount
  namespace: heptio-sonobuoy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.5.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-heptio-sonobuoy-sonobuoy-serviceaccount
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
  namespace: e2e-tests-proxy-2kr5h
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
subjects:
- kind: ServiceAccount
  name: sonobuoy-serviceaccount
  namespace: heptio-sonobuoy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.5.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-heptio-sonobuoy-sonobuoy-serviceaccount
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: audit2rbac:system:serviceaccount:heptio-sonobuoy:sonobuoy-serviceaccount
subjects:
- kind: ServiceAccount
  name: sonobuoy-serviceaccount
  namespace: heptio-sonobuoy
```
