### ISSUE TITLE
Large result tarball causing complete scan failures

### ISSUE THREAD

**Issue by rdodev** [heptio/sonobuoy#199]
While on-site at a customer, sonobuoy scanner kept crashing after running for >1 hour. 

Pertinent logs have been sent to @chuckha and @timothysc

**Comment by chuckha** [comment]
this config is generating a large (>10M) archive.

```yaml
---
apiVersion: v1
data:
  config.json: |
    {
        "Description": "sonobuoy run for scanner.heptio.com",
        "Filters": {
            "LabelSelector": "",
            "Namespaces": ".*"
        },
        "PluginNamespace": "heptio-sonobuoy",
        "Plugins": [
            {
                "name": "e2e"
            }
        ],
        "Resources": [
            "Nodes",
            "ServerVersion"
        ],
        "ResultsDir": "/tmp/sonobuoy",
        "Server": {
            "advertiseaddress": "sonobuoy-master:8080",
            "bindaddress": "0.0.0.0",
            "bindport": 8080,
            "timeoutseconds": 5400
        },
        "Version": "v0.10.0"
    }
kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-config-cm
  namespace: heptio-sonobuoy
---
```
