### ISSUE TITLE
GenConfig has no defaults

### ISSUE THREAD

**Issue by chuckha** [heptio/sonobuoy#286]
There are no defaults on GenConfig. It would be nice to be able to generate sonobuoy YAML without having to know anything.

Reproduce:

```
	generateOptions := &client.GenConfig{
		E2EConfig: &client.E2EConfig{
			Focus: testCases.Focus(),
		},
		Config: GetConfigWithMode(&SonobuoyConfig{}, client.Quick),
	}

	bytes, err := client.NewSonobuoyClient().GenerateManifest(generateOptions)
```
=> 
```
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - /sonobuoy master --no-exit=true -v 3 --logtostderr
    image:  # problem is here, it is empty but it should be :latest or :master of sonobuoy
    imagePullPolicy: Always
```
