### ISSUE TITLE
Unable to add new VolumeMounts to latest version of Sonobuoy plugins

### ISSUE THREAD

**Issue by KannanThiru** [heptio/sonobuoy#387]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug/Feature or Not documented for latest version of Sonobuoy

**What happened**:
We are developing CIS plugin for docker. We are trying to add 3 more volume to plugin.. Looks like we are unable to add in latest version of Sonobuoy and volumes are predefined. Any help appreciated!

**What you expected to happen**:
We able to add new volumes to plugin in V0.10.0. When migrating to new sonobuoy version we are unable add new volumes. Looks like volumes are predefined [here](https://github.com/heptio/sonobuoy/blob/master/pkg/plugin/driver/daemonset/template.go#L95-L99) and unable to add additional volumeMounts.

```
      volumeMounts:
      - mountPath: /tmp/results
        name: results
        readOnly: false
      - mountPath: /var/lib
        name: var-lib
        readOnly: false
      - mountPath: /var/run/docker.sock
        name: docker-sock
        readOnly: false
      - mountPath: /usr/lib/systemd
        name: systemd
        readOnly: false
```

**How to reproduce it (as minimally and precisely as possible)**:
Adding new volumeMount to plugin

**Anything else we need to know?**:

**Environment**:
v0.11.0-rc.2
- Kubernetes version (use `kubectl version`): 1.9.3

**Comment by liztio** [comment]
```yaml
---
sonobuoy-config:
  driver: Job
  plugin-name: e2e
  result-type: e2e
spec:
  env:
  - name: E2E_FOCUS
    value: Pods should be submitted and removed
  image: gcr.io/heptio-images/kube-conformance:latest
  imagePullPolicy: Always
  name: e2e
  volumeMounts:
  - mountPath: /tmp/results
    name: results
    readOnly: false
  - mountPath: /var/lib
     name: test-volume
extraVolumes:
- name: test-volume
    awsElasticBlockStore:
      volumeID: <volume-id>
      fsType: ext4
```

@KannanThiru would something like this solve your problem?

**Comment by KannanThiru** [comment]
@liztio Yes. This helps if we still able to mount host paths.

**Comment by timothysc** [comment]
So is there any fix here?  I suppose we could comment update our example plugins.

**Comment by KannanThiru** [comment]
@liztio @timothysc Thanks for fixing this issue.

**Comment by KannanThiru** [comment]
@liztio @timothysc I tried with both master and latest sonobuoy images. Still i am facing same issue.

```
time="2018-03-26T06:47:43Z" level=error msg="error running plugins: error running plugin docker-cis: could not create DaemonSet for daemonset plugin docker-cis: DaemonSet.apps \"sonobuoy-docker-cis-daemon-set-2b2005e29d9e43ed\" is invalid: [spec.template.spec.containers[0].volumeMounts[1].name: Not found: \"var-lib\", spec.template.spec.containers[0].volumeMounts[2].name: Not found: \"docker-sock\", spec.template.spec.containers[0].volumeMounts[3].name: Not found: \"systemd\"]"
```

**this is my plugin config**
```
apiVersion: v1
data:
  docker_cis.yaml: |
    sonobuoy-config:
      driver: DaemonSet
      plugin-name: docker-cis
      result-type: docker_cis
    spec:
      env:
      - name: CHECKS
        value: check_2_2,check_2_3,check_5_26
      - name: SKIP_CONTAINERS
        value: kube-system
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: RESULTS_DIR
        value: /tmp/results
      - name: RESULT_TYPE
        value: docker_cis
      image: kannanthiru/sonobuoy-plugin-docker-cis:latest
      imagePullPolicy: Always
      name: sonobuoy-docker-cis-config
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /tmp/results
        name: results
        readOnly: false
      - mountPath: /var/lib
        name: var-lib
      - mountPath: /var/run/docker.sock
        name: docker-sock
      - mountPath: /usr/lib/systemd
        name: systemd
    extra-volumes:
    - name: var-lib
      hostPath:
        path: /var/lib
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: systemd
      hostPath:
        path: /usr/lib/systemd
kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-plugins-cm
  namespace: heptio-sonobuoy
```

Please let me know if I have missed anything.
