### ISSUE TITLE
Using a config without a UUID results in an error when writing results

### ISSUE THREAD

**Issue by zubron** [heptio/sonobuoy#806]
**What steps did you take and what happened:**
Originally reported by @MengmengZHANG, it was noticed that if you provide a config to sonobuoy without a UUID, it will fail to collect the results for the run. This behaviour can be demonstrated by running `sonobuoy gen` and then modifying the `config.json` data within the `sonobuoy-config-cm` and removing the `UUID` field:

```
apiVersion: v1
data:
  config.json: |
    {"Description":"DEFAULT","Version":"v0.15.0","ResultsDir":"/tmp/sonobuoy","Resources":["apiservices","certificatesigningrequests","clusterrolebindings","clusterroles","componentstatuses","configmaps","controllerrevisions","cronjobs","customresourcedefinitions","daemonsets","deployments","endpoints","ingresses","jobs","leases","limitranges","mutatingwebhookconfigurations","namespaces","networkpolicies","nodes","persistentvolumeclaims","persistentvolumes","poddisruptionbudgets","pods","podlogs","podsecuritypolicies","podtemplates","priorityclasses","replicasets","replicationcontrollers","resourcequotas","rolebindings","roles","servergroups","serverversion","serviceaccounts","services","statefulsets","storageclasses","validatingwebhookconfigurations","volumeattachments"],"Filters":{"Namespaces":".*","LabelSelector":""},"Limits":{"PodLogs":{"Namespaces":"","SonobuoyNamespace":true,"FieldSelectors":[],"LabelSelector":"","Previous":false,"SinceSeconds":null,"SinceTime":null,"Timestamps":false,"TailLines":null,"LimitBytes":null,"LimitSize":"","LimitTime":""}},"QPS":30,"Burst":50,"Server":{"bindaddress":"0.0.0.0","bindport":8080,"advertiseaddress":"","timeoutseconds":10800},"Plugins":[{"name":"systemd-logs"}],"PluginSearchPath":["./plugins.d","/etc/sonobuoy/plugins.d","~/sonobuoy/plugins.d"],"Namespace":"heptio-sonobuoy","WorkerImage":"gcr.io/heptio-images/sonobuoy:v0.15.0","ImagePullPolicy":"IfNotPresent","ImagePullSecrets":""}
kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-config-cm
  namespace: heptio-sonobuoy
```

Using this manifest (running `kubectl apply -f <generated_manifest.yml>`), the following error will eventually be shown in the output from `sonobuoy logs`:

```
time="2019-07-17T16:31:13Z" level=error msg="error assembling results tarball: archive/tar: write too long"
time="2019-07-17T16:31:13Z" level=info msg="Results available at /tmp/sonobuoy/201907171631_sonobuoy_.tar.gz"
time="2019-07-17T16:31:13Z" level=info msg="no-exit was specified, sonobuoy is now blocking"
```
Retrieving these results will appear to be successful, but the resulting tarball will contain a tarball with the same name which is invalid because the write failed. We can see from the logs that the tarball name is missing the UUID: `201907171631_sonobuoy_.tar.gz`. Within [`discovery.Run`](https://github.com/heptio/sonobuoy/blob/master/pkg/discovery/discovery.go#L65), the UUID is used to create a unique directory to store the results in. Since the UUID is empty, this is not generated. Later, a [tarball is created within this directory](https://github.com/heptio/sonobuoy/blob/master/pkg/discovery/discovery.go#L186-L187), and the directory is added to the tarball which results in the tarball being added to itself and causes the write error.

**What did you expect to happen:**
In previous versions of Sonobuoy (up to v0.14.2), the loaded config was merged with a [default config](https://github.com/heptio/sonobuoy/blob/v0.14.2/pkg/config/loader.go#L35). This meant that if a UUID was not provided, it would be generated. This behaviour is now a regression, sonobuoy should still generate a UUID if not provided in the config.

**Environment:**
- Sonobuoy version: v0.15.0
- Kubernetes version: (use `kubectl version`): v.1.15.0 (client and server)
